/*
 * @brief An ENUM where each represents an option that the user can interact with
 */
public enum MenuOption
{
  ADD_USER,
  ADD_USERS,
  UPDATE_USER,
  DELETE_USER,
  DELETE_USERS,
  ADD_ACCOUNT_V1,
  ADD_ACCOUNT_V2,
  DELETE_ACCOUNT,
  UPDATE_ACCOUNT,
  ADD_PRE_BUNDLE,
  ADD_PAC_BUNDLE_V1,
  ADD_PAC_BUNDLE_V2,
  ADD_PAC_BUNDLE_V3,
  LIST_USER_DETAILS,
  LIST_ALL_USERS,
  LIST_ACCOUNT,
  LIST_ACCOUNTS,
  LIST_MONTHLY_FEES,
  LIST_MONTHLY_FEES_ALL,
  LIST_BUNDLE_DETAILS,
  LIST_ALL_PRE_BUNDLES,
  LIST_ALL_PAC_BUNDLES
}

